Repository Manish1Gupta/Coding-Community-Contributions, pull requests merged in 2022-10, with the labels that each got.

#2 Create Check_Leap_Year.cpp
  Check_Leap_Year.cpp
Labels: good first issue, hacktoberfest2022

#34 Added Parenthesis matching
  Parenthesis Matching.cpp
Labels: hacktoberfest2022

#128 Create Fibonacci Series
  Fibonacci Series
Labels: invalid, spam
